version: '3.8'

services:
  wulong:
    image: julienberanger/wulong:latest
    pull_policy: always
    ports:
      - "3000:3000"
    volumes:
      - /var/run/dstack.sock:/var/run/dstack.sock
      - wulong-data:/app/data
    environment:
      - NODE_ENV=${NODE_ENV}
      - KMS_URL=${KMS_URL}
      - CHEST_PATH=/app/data/chest.json
    restart: unless-stopped

volumes:
  wulong-data:
